### ISSUE TITLE
Master doesn't compile on Qt 5.7.1

### ISSUE THREAD

**Issue by Gui13** [QuiteRSS/quiterss#1006]
I know it is said in INSTALL that I should be using Qt 5.4.*, but I tried with 5.7.1 (what the last ubuntu ships with), and I can't compile.

I'm rather surprised that you can compile even in 5.4, since there are changes that should have broken the compilation, namely:

- `#include <QtGui/*>` don't work with qt5, you have to use `#include <QtWidgets/*>` or just `#include <*>`
- `QApplication::UnicodeUTF8` doesn't exist in Qt5, you shouldn't be able to use it.

See here: https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5

This is where I'm stuck right now:

```
In file included from ../src/adblock/adblockaddsubscriptiondialog.cpp:36:0:
../../quiterss/ui_adblockaddsubscriptiondialog.h: In member function ‘void Ui_AdBlockAddSubscriptionDialog::retranslateUi(QDialog*)’:
../../quiterss/ui_adblockaddsubscriptiondialog.h:92:133: error: ‘UnicodeUTF8’ is not a member of ‘QApplication’
         AdBlockAddSubscriptionDialog->setWindowTitle(QApplication::translate("AdBlockAddSubscriptionDialog", "Add Subscription", 0, QApplication::UnicodeUTF8));
                                                                                                                                     ^~~~~~~~~~~~
../../quiterss/ui_adblockaddsubscriptiondialog.h:93:93: error: ‘UnicodeUTF8’ is not a member of ‘QApplication’
         label->setText(QApplication::translate("AdBlockAddSubscriptionDialog", "Title:", 0, QApplication::UnicodeUTF8));
                                                                                             ^~~~~~~~~~~~
../../quiterss/ui_adblockaddsubscriptiondialog.h:94:97: error: ‘UnicodeUTF8’ is not a member of ‘QApplication’
         label_2->setText(QApplication::translate("AdBlockAddSubscriptionDialog", "Address:", 0, QApplication::UnicodeUTF8));
                                                                                                 ^~~~~~~~~~~~
../../quiterss/ui_adblockaddsubscriptiondialog.h:95:121: error: ‘UnicodeUTF8’ is not a member of ‘QApplication’
         label_3->setText(QApplication::translate("AdBlockAddSubscriptionDialog", "Add new subscription to AdBlock:", 0, QApplication::UnicodeUTF8));

```

Do you have any idea if it is supposed to compile in qt5 ?

**Comment by Funcy-dcm** [comment]
I have Qt 5.6 compiled normally but in Mac OS X.
I borrowed this code, I'll try to rewrite it

**Comment by Funcy-dcm** [comment]
Have you compiled this project before with another version of Qt?

**Comment by Funcy-dcm** [comment]
> #include <QtGui/*> don't work with qt5, you have to use #include <QtWidgets/*> or just #include <*>

These lines are in the file ui_adblockaddsubscriptiondialog.h. This file is created by the compiler itself.
You need to clean the project and rebuild it
